#!/bin/bash

echo "🚨 URGENT: RLS POLICIES FIX REQUIRED"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "❌ ERROR: Empty Supabase error {} means RLS is blocking access!"
echo ""
echo "✅ SOLUTION: Run this SQL in your Supabase Dashboard"
echo ""
echo "📋 STEP-BY-STEP INSTRUCTIONS:"
echo ""
echo "1. Open this URL in your browser:"
echo "   👉 https://supabase.com/dashboard/project/vhoarjcbkcptqlyfdhsx"
echo ""
echo "2. Click 'SQL Editor' in the left sidebar"
echo ""
echo "3. Click '+ New Query' button"
echo ""
echo "4. Copy the SQL below and paste it into the editor:"
echo ""
echo "═══════════════════════════════════════════════════════════"
cat /Users/jaan/Desktop/Hackathon/FIX_CHALLENGES_RLS.sql
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "5. Click 'RUN' button (or press Cmd+Enter)"
echo ""
echo "6. Wait for 'Success' message"
echo ""
echo "7. Refresh your browser at http://localhost:3000"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "💡 WHY THIS IS NEEDED:"
echo "   - Supabase has Row Level Security (RLS) enabled"
echo "   - By default, RLS blocks ALL access"
echo "   - We need to create policies to allow reading challenges"
echo "   - This SQL creates policies for challenges, submissions, and profiles"
echo ""
echo "⏰ This takes only 30 seconds to fix!"
echo ""
