#!/bin/bash

echo "🔓 DISABLE RLS FOR TESTING"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "This will disable ALL Row Level Security policies"
echo "so you can test freely without permission issues."
echo ""
echo "⚠️  WARNING: Only for development/testing!"
echo "   Do NOT use this in production!"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📋 INSTRUCTIONS:"
echo ""
echo "1. Open Supabase Dashboard:"
echo "   👉 https://supabase.com/dashboard/project/vhoarjcbkcptqlyfdhsx/editor/sql"
echo ""
echo "2. Click '+ New Query'"
echo ""
echo "3. Copy this SQL:"
echo ""
echo "═══════════════════════════════════════════════════════════"
cat /Users/jaan/Desktop/Hackathon/DISABLE_RLS.sql
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "4. Click 'RUN' (or press Cmd+Enter)"
echo ""
echo "5. You should see: 'RLS DISABLED - All tables are now open!'"
echo ""
echo "6. Refresh your browser: http://localhost:3001"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✅ After running this:"
echo "   • No more empty {} errors"
echo "   • All pages will load data"
echo "   • Competitions will display"
echo "   • Submissions will work"
echo "   • No permission issues"
echo ""
echo "🚀 Your app will work immediately!"
echo ""
